-- T?o b?ng LOP
CREATE TABLE LOP
(
	MALOP CHAR(10),
	TENLOP VARCHAR(40),
	SISO TINYINT,
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
)
GO
-- T?O B?NG SINHVIEN
CREATE TABLE SINHVIEN
(
	MASV CHAR(15),
	HOTEN VARCHAR(40),
	NGAYSINH SMALLDATETIME,
	MALOP CHAR(10),
	CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV)
)
-- T?o b?ng MONHOC
	CREATE TABLE MONHOC
	(
		MAMH VARCHAR(10),
		TENMH VARCHAR(40),
		CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH)
	)
	GO
-- T?o b?ng KETQUA
CREATE TABLE KETQUA
(
	MASV CHAR(5),
	MAMH VARCHAR(10),
	DIEMTHI NUMERIC(4,2),
	CONSTRAINT PK_KETQUA PRIMARY KEY (MASV, MAMH)
)
GO

--CÂU 1
create function F_DiemTB(@MASV varchar(10))
returns float
as
begin
declare @kq float
select @kq=avg(tb1.DIEMTHI)from 
(select distinct KetQua.MaSV, dbo.F_DIEMTHI(@MASV,KETQUA.MAMH) as DIEMTHI from KETQUA 
where KETQUA.MASV=@MASV)as tb1
return @kq
end
